### ISSUE TITLE
Task list example

### ISSUE THREAD

**Issue by FerneyOAmaya** [FerneyOAmaya/Innovacion#2]
- [x] Colocado el issue
- [] En progreso
- [ ] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
